nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization','X-Requested-With', 'X-Public-Token']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null