FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    unzip \
    libpq-dev \
    libzip-dev \
    zip \
    && docker-php-ext-install pdo pdo_pgsql zip \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install sockets pdo pdo_pgsql zip
RUN pecl install redis && docker-php-ext-enable redis

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . /var/www/html/

RUN composer run-script post-install-cmd || true

RUN composer install --optimize-autoloader --no-dev

RUN chown -R www-data:www-data /var/www/html/var/cache

RUN php bin/console doctrine:cache:clear-metadata --env=prod --no-debug

RUN php bin/console cache:clear --env=prod --no-debug
RUN php bin/console cache:warmup --env=prod --no-debug

EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm"]