services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: syapi
    working_dir: /var/www/html
    volumes:
      - ./var/www
    depends_on:
      - db
      - redis
    networks:
      - main

  node:
    build:
      context: ./nodeService
      dockerfile: Dockerfile.prod
    container_name: nodeService
    networks:
      - main

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - main

  db:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - main

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - main

networks:
  main:

volumes:
  database_data:
  redis_data:
